name: Dispatch test

on: workflow_dispatch
  
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name : Show dispatch context
              run: |
                echo var.GITHUB_SHA : ${{ vars.GITHUB_SHA }}
                echo var.GITHUB_HEAD_REF : ${{ vars.GITHUB_HEAD_REF }}
                echo var.GITHUB_REF : ${{ vars.GITHUB_REF }}
                echo github.head_ref : ${{ github.head_ref }}
                echo github.ref_name : ${{ github.ref_name }}
