name: Dispatch test

on: workflow_dispatch
  
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name : Show dispatch context
              run: |
                echo GITHUB_SHA ${{ vars.GITHUB_SHA }}
                echo GITHUB_HEAD_REF ${{ vars.GITHUB_HEAD_REF }}
                echo GITHUB_REF ${{ vars.GITHUB_REF }}
