name: Rust

on: workflow_dispatch
  
env:
  CARGO_TERM_COLOR: always

jobs:
  client_matrix:
    strategy:
      matrix:
        rust_channel: ["stable", "nightly"]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Cap'n Proto
      run: choco install capnproto
    - name: run capnp.exe --help
      run: capnp.exe --help
    - if: matrix.rust_channel == 'nightly'
      name: Install Nightly Toolchain
      run: rustup toolchain install nightly
    - name: Build
      run: .scripts\build.ps1
      env:
        rust_channel: ${{ matrix.rust_channel }}
    - name: Get Version
      run: |
        git fetch --prune --unshallow --tags
        "APP_VERSION=$(git describe --tags)" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Release Build-$APP_VERSION-${{ matrix.rust_channel }}
        path: target/release
        retention-days: 5
