name: Rust

on: workflow_dispatch
  
env:
  CARGO_TERM_COLOR: always
  capn_url: https://capnproto.org/capnproto-c++-win32-1.0.2.zip
  capn_path: capnproto-tools-win32-1.0.2
  capn_bin: capnp.exe

jobs:
  client_matrix:
    strategy:
      matrix:
        rust_channel: ["stable", "nightly"]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    # - name: Install Cap'n Proto
    #   run: choco install capnproto
    - name: Install Cap'n Proto
      uses: engineerd/configurator@v0.0.1
      with:
        name: ${{ env.capn_bin }}
        url: ${{ env.capn_url}}
        pathInArchive: ${{ env.capn_path }}

    - name: run capnp.exe --help
      run: capnp.exe --help
      
    - if: matrix.rust_channel == 'nightly'
      name: Install Nightly Toolchain
      run: rustup toolchain install nightly
    - name: Build
      run: .scripts\build.ps1
      env:
        rust_channel: ${{ matrix.rust_channel }}
    - name: Get Version
      run: |
        git fetch --prune --unshallow --tags
        "APP_VERSION=$(git describe --tags)" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Release Build-${{ env.APP_VERSION }}-${{ matrix.rust_channel }}
        path: target/release
        retention-days: 5
